import React from 'react';
import { createRoot } from 'react-dom/client';
import { Activity, AlertTriangle, ArrowUpRight, Database, Gauge, Radio, ShieldCheck } from 'lucide-react';
import './styles.css';
import { getIntegrationReadiness } from './services/api';

const pending = 'PENDING TEAM INPUT';

function ComponentRow({ name, detail, requiredInputs }) {
  return <div className="component-row"><div className="component-icon"><Database size={18} /></div><div className="component-copy"><strong>{name}</strong><span>{detail}</span>{requiredInputs?.[0] && <small>Needs: {requiredInputs[0]}</small>}</div><span className="status-pill"><span />Awaiting input</span></div>;
}

function App() {
  const [readiness, setReadiness] = React.useState(null);
  const [error, setError] = React.useState('');
  React.useEffect(() => { getIntegrationReadiness().then(setReadiness).catch(() => setError('API unavailable. Start the backend to connect live readiness status.')); }, []);
  const components = readiness?.components || ['Data Engineer', 'EDA Engineer', 'ML Engineer', 'Evaluation Engineer'].map(name => ({ name, detail: pending, requiredInputs: [pending] }));
  return <div className="shell"><aside><div className="brand"><div className="brand-mark"><Radio size={20} /></div><div><b>CRISIS</b><span>COMMAND</span></div></div><nav><a className="active"><Activity size={17} /> Situation room</a><a><Gauge size={17} /> Model readiness</a><a><ShieldCheck size={17} /> Integrations</a></nav><div className="sidebar-foot"><span className="live-dot" /> System foundation<br /><small>Stage-01 ML</small></div></aside><main><header><div><p className="eyebrow">OPERATIONS / STAGE 01</p><h1>Integration control room</h1><p className="lede">A clear view of what is connected, what is waiting, and what must be approved before decisions can run.</p></div><div className="header-status"><span className="status-dot" /> FOUNDATION MODE</div></header><section className="hero-strip"><div><p className="eyebrow">CURRENT POSTURE</p><h2>Awaiting team data</h2><p>The decision engine is structurally ready. Operational outputs will appear only after all four team contracts are approved.</p></div><div className="hero-number">{readiness?.status === 'ready' ? 'READY' : '—'}</div></section>{error && <div className="notice"><AlertTriangle size={18} />{error}</div>}<section className="grid"><div className="panel readiness"><div className="panel-heading"><div><p className="eyebrow">READINESS CHECK</p><h3>Integration inputs</h3></div><ArrowUpRight size={19} /></div><div className="component-list">{components.map(component => <ComponentRow key={component.name} {...component} />)}</div></div><div className="panel empty-panel"><div className="empty-icon"><Gauge size={21} /></div><p className="eyebrow">LIVE DECISIONS</p><h3>ML model not connected</h3><p>Risk scores, alerts, and recommendations remain unavailable until the finalized ML inference contract is supplied.</p><span className="outline-label">{pending}</span></div></section><section className="footer-note"><ShieldCheck size={17} /><span>Guardrail active: no predictions or disaster values are generated by this foundation.</span></section></main></div>;
}

createRoot(document.getElementById('root')).render(<App />);
